'use strict';

module.exports = {
  AdminRule: {
    account: {
      type: 'string',
      required: true,
      allowEmpty: false,
      message: '管理员账号不能为空',
      min: 5,
      max: 20,
    },
    user_name: {
      type: 'string',
      required: true,
      allowEmpty: false,
      message: '管理员用户名不能为空',
      min: 2,
      max: 10,
    },
    pwd: {
      type: 'string',
      required: true,
      allowEmpty: false,
      message: '管理员密码不能为空',
    },
    role: {
      type: 'enum',
      required: false,
      allowEmpty: true,
      values: [ 'ADMIN', 'STUDENT', 'TEACHER' ],
    },
  },

  DeptRule: {
    d_id: {
      type: 'string',
      required: true,
      allowEmpty: false,
      format: /^[1-9]\d*$/,
      message: '院系编号不能为空,而且必须为数字,首位不能为0',
      min: 1,
      max: 20,
    },
    d_name: {
      type: 'string',
      required: true,
      allowEmpty: false,
      message: '院系名称不能为空',
      min: 2,
      max: 30,
    },
    d_info: {
      type: 'string',
      required: false,
      allowEmpty: true,
      min: 0,
      max: 255,
    },
  },

  MajorRule: {
    m_id: {
      type: 'string',
      required: true,
      allowEmpty: false,
      format: /^[1-9]\d*$/,
      message: '专业编号不能为空,而且必须为数字,首位不能为0',
      min: 1,
      max: 20,
    },
    d_id: {
      type: 'string',
      required: true,
      allowEmpty: false,
      format: /^[1-9]\d*$/,
      message: '院系编号不能为空,而且必须为数字,首位不能为0',
      min: 1,
      max: 20,
    },
    m_info: {
      type: 'string',
      required: false,
      allowEmpty: true,
      min: 0,
      max: 255,
    },
  },

  StudentRule: {
    s_id: {
      type: 'string',
      required: true,
      allowEmpty: false,
      format: /^[1-9]\d*$/,
      message: '学号不能为空,且必须为数字,首位不能为0',
      min: 5,
      max: 20,
    },
    m_id: {
      type: 'string',
      required: true,
      allowEmpty: false,
      format: /^[1-9]\d*$/,
      message: '专业编号不能为空,而且必须为数字,首位不能为0',
      min: 1,
      max: 20,
    },
    s_name: {
      type: 'string',
      required: true,
      allowEmpty: false,
      message: '姓名不能为空',
      min: 2,
      max: 5,
    },
    sex: {
      type: 'enum',
      required: true,
      allowEmpty: false,
      values: [ '男', '女' ],
    },
    phone: {
      type: 'string',
      required: false,
      allowEmpty: true,
      format: /^(13[0-9]|14[579]|15([0-3]|[5-9])|16[6]|17[0135678]|18[0-9]|19[89])\d{8}$/,
      message: '不是正确格式的电话号码',
    },
    role: {
      type: 'enum',
      required: false,
      allowEmpty: true,
      values: [ 'ADMIN', 'STUDENT', 'TEACHER' ],
    },
  },

  TeacherRule: {
    t_id: {
      type: 'string',
      required: true,
      allowEmpty: false,
      format: /^[1-9]\d*$/,
      message: '教师工号不能为空,且必须为数字,首位不能为0',
      min: 5,
      max: 20,
    },
    t_name: {
      type: 'string',
      required: true,
      allowEmpty: false,
      message: '姓名不能为空',
      min: 2,
      max: 5,
    },
    sex: {
      type: 'enum',
      required: true,
      allowEmpty: false,
      values: [ '男', '女' ],
    },
    job: {
      type: 'enum',
      required: false,
      allowEmpty: true,
      values: [ '讲师', '教授', '副教授' ],
    },
    count: {
      type: 'number',
      required: true,
      allowEmpty: false,
      min: 0,
      max: 20,
    },
    phone: {
      type: 'string',
      required: false,
      allowEmpty: true,
      format: /^(13[0-9]|14[579]|15([0-3]|[5-9])|16[6]|17[0135678]|18[0-9]|19[89])\d{8}$/,
      message: '不是正确格式的电话号码',
    },
    role: {
      type: 'enum',
      required: false,
      allowEmpty: true,
      values: [ 'ADMIN', 'STUDENT', 'TEACHER' ],
    },
  },

  StudentCourseRule: {
    s_id: {
      type: 'string',
      required: true,
      allowEmpty: false,
      format: /^[1-9]\d*$/,
      message: '学号不能为空,且必须为数字,首位不能为0',
      min: 5,
      max: 20,
    },
    c_id: {
      type: 'string',
      required: true,
      allowEmpty: false,
      format: /^[1-9]\d*$/,
      message: '课程编号不能为空,而且必须为数字,首位不能为0',
      min: 1,
      max: 20,
    },
    score: {
      type: 'number',
      required: false,
      allowEmpty: false,
      min: 0,
      max: 100,
    },
    second_score: {
      type: 'number',
      required: false,
      allowEmpty: false,
      min: 0,
      max: 100,
    },
    is_publish: {
      type: 'string',
      required: false,
      allowEmpty: true,
      values: [ '未公布', '已公布' ],
    },
  },

  CourseRule: {
    c_id: {
      type: 'string',
      required: true,
      allowEmpty: false,
      format: /^[1-9]\d*$/,
      message: '课程编号不能为空,而且必须为数字,首位不能为0',
      min: 1,
      max: 20,
    },
    t_id: {
      type: 'string',
      required: true,
      allowEmpty: false,
      format: /^[1-9]\d*$/,
      message: '课程编号不能为空,而且必须为数字,首位不能为0',
      min: 1,
      max: 20,
    },
    c_name: {
      type: 'string',
      required: true,
      allowEmpty: false,
      message: '课程名称不能为空',
      min: 2,
      max: 30,
    },
    c_info: {
      type: 'string',
      required: false,
      allowEmpty: true,
      min: 0,
      max: 255,
    },
    credit: {
      type: 'enum',
      required: true,
      allowEmpty: false,
      min: 0.5,
      max: 4.5,
      values: [ 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5 ],
    },
    count: {
      type: 'number',
      required: true,
      allowEmpty: false,
      min: 0,
      max: 100,
    },
  },

  DeleteRule: {
    id: {
      type: 'array',
      required: true,
      allowEmpty: false,
    },
  },

  LoginRule: {
    account: {
      type: 'string',
      required: true,
      allowEmpty: false,
      message: '用户账号不能为空',
      min: 5,
      max: 20,
    },
    pwd: {
      type: 'string',
      required: true,
      allowEmpty: false,
      message: '用户密码不能为空',
    },
    role: {
      type: 'enum',
      required: true,
      allowEmpty: false,
      values: [ 'ADMIN', 'STUDENT', 'TEACHER' ],
    },
    rememberMe: {
      type: 'boolean',
      required: false,
      allowEmpty: false,
      defaultValue: false,
    },
  },

  PwdRule: {
    old_password: {
      type: 'string',
      required: true,
      allowEmpty: false,
      message: '旧密码不能为空',
    },
    new_password: {
      type: 'string',
      required: true,
      allowEmpty: false,
      message: '新密码不能为空',
    },
    repeat_password: {
      type: 'string',
      required: true,
      allowEmpty: false,
      message: '再次输入的密码不能为空',
    },
  },

};
